authors:
  gekkotadev:
    name: gekkotadev (Jeremy)
    description: Programming, Game Design, Documentation
    avatar: https://avatars.githubusercontent.com/u/114091010
    url: https://github.com/gekkotadev
