site_name: Sierra Verde Documentation

extra_css:
  - stylesheets/index.css

theme:
  name: material
  features:
    - content.tooltips
    - footnotes
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.follow

markdown_extensions: 
  - abbr
  - attr_list
  - pymdownx.snippets

plugins:
  - blog
  - meta
  - tags
  - privacy:
      enabled: !ENV [PRODUCTION, false]
  - offline:
      enabled: !ENV [OFFLINE, false]
  - search
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

nav:
  - Documentation: index.md
  - Dev Logs:
    - blog/index.md
